CREATE TABLE SIGNO(
    CODIGO NUMBER(18) NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DIA_INICIAL NUMBER(2) NOT NULL,
    DIA_FINAL NUMBER(2) NOT NULL,
    MES_INICIAL NUMBER(2) NOT NULL,
    MES_FINAL NUMBER(2)
);

CREATE SEQUENCE SEQ_SIGNO
START WITH 1
INCREMENT BY 1;

CREATE TABLE PESSOA(
    CODIGO NUMBER(18) NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    CODIGO_SIGNO NUMBER(18) NOT NULL,
    CONSTRAINT FK_PESSOA_SIGNO FOREIGN KEY (CODIGO_SIGNO) REFERENCES SIGNO(CODIGO)
);

CREATE SEQUENCE SEQ_PESSOA
START WITH 1
INCREMENT BY 1;

INSERT INTO SIGNO (CODIGO, NOME, DIA_INICIAL, DIA_FINAL, MES_INICIAL, MES_FINAL)
VALUES (SEQ_SIGNO.NEXTVAL, 'Aquario', 20, 18, 1, 2);
INSERT INTO SIGNO (CODIGO, NOME, DIA_INICIAL, DIA_FINAL, MES_INICIAL, MES_FINAL)
VALUES (SEQ_SIGNO.NEXTVAL, 'Peixes', 19, 20, 2, 3);
INSERT INTO SIGNO (CODIGO, NOME, DIA_INICIAL, DIA_FINAL, MES_INICIAL, MES_FINAL)
VALUES (SEQ_SIGNO.NEXTVAL, 'Aries', 21, 19, 3, 4);
INSERT INTO SIGNO (CODIGO, NOME, DIA_INICIAL, DIA_FINAL, MES_INICIAL, MES_FINAL)
VALUES (SEQ_SIGNO.NEXTVAL, 'Touro', 20, 20, 4, 5);
INSERT INTO SIGNO (CODIGO, NOME, DIA_INICIAL, DIA_FINAL, MES_INICIAL, MES_FINAL)
VALUES (SEQ_SIGNO.NEXTVAL, 'Gemeos', 21, 20, 5, 6);
INSERT INTO SIGNO (CODIGO, NOME, DIA_INICIAL, DIA_FINAL, MES_INICIAL, MES_FINAL)
VALUES (SEQ_SIGNO.NEXTVAL, 'Cancer', 21, 22, 6, 7);
INSERT INTO SIGNO (CODIGO, NOME, DIA_INICIAL, DIA_FINAL, MES_INICIAL, MES_FINAL)
VALUES (SEQ_SIGNO.NEXTVAL, 'Leao', 23, 22, 7, 8);
INSERT INTO SIGNO (CODIGO, NOME, DIA_INICIAL, DIA_FINAL, MES_INICIAL, MES_FINAL)
VALUES (SEQ_SIGNO.NEXTVAL, 'Virgem', 23, 22, 8, 9);
INSERT INTO SIGNO (CODIGO, NOME, DIA_INICIAL, DIA_FINAL, MES_INICIAL, MES_FINAL)
VALUES (SEQ_SIGNO.NEXTVAL, 'Libra', 23, 22, 9, 10);
INSERT INTO SIGNO (CODIGO, NOME, DIA_INICIAL, DIA_FINAL, MES_INICIAL, MES_FINAL)
VALUES (SEQ_SIGNO.NEXTVAL, 'Escorpiao', 23, 21, 10, 11);
INSERT INTO SIGNO (CODIGO, NOME, DIA_INICIAL, DIA_FINAL, MES_INICIAL, MES_FINAL)
VALUES (SEQ_SIGNO.NEXTVAL, 'Sagitario', 22, 21, 11, 12);
INSERT INTO SIGNO (CODIGO, NOME, DIA_INICIAL, DIA_FINAL, MES_INICIAL, MES_FINAL)
VALUES (SEQ_SIGNO.NEXTVAL, 'Sagitario', 22, 19, 12, 1);
COMMIT;

